export const typeEmojiColorMap: { [key: string]: { emoji: string, color: string } } = {
  grass: { emoji: '🌿', color: 'text-green-500' },
  poison: { emoji: '☠️', color: 'text-purple-500' },
  fire: { emoji: '🔥', color: 'text-red-500' },
  flying: { emoji: '🕊️', color: 'text-blue-300' },
  water: { emoji: '💧', color: 'text-blue-500' },
  bug: { emoji: '🐛', color: 'text-green-700' },
  normal: { emoji: '⚪', color: 'text-gray-500' },
  electric: { emoji: '⚡', color: 'text-yellow-500' },
  ground: { emoji: '🌍', color: 'text-brown-500' },
  fairy: { emoji: '✨', color: 'text-pink-500' },
  fighting: { emoji: '🥊', color: 'text-red-700' },
  psychic: { emoji: '🔮', color: 'text-purple-300' },
  rock: { emoji: '🪨', color: 'text-gray-700' },
  steel: { emoji: '🔩', color: 'text-gray-400' },
  ice: { emoji: '❄️', color: 'text-blue-200' },
  ghost: { emoji: '👻', color: 'text-purple-700' },
  dragon: { emoji: '🐉', color: 'text-red-900' },
};